name: Continuous Integration
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build debug apk with Gradle
      run: cd android && ./gradlew clean assemble
    - uses: actions/upload-artifact@v2
      with:
        name: aether
        path: android/app/build/outputs/apk/debug/app-debug.apk